import type { NegativeItem } from "../types";
// BUG-03 FIX: Use centralized currency normalizer instead of inline normalizeCurrency()
import { normalizeCurrencyToCents } from "./currencyNormalizer";

export type HallucinationReason =
  | "invented_date"
  | "invented_balance"
  | "invented_account_detail"
  | "unknown_citation";

export interface GroundedLetterContext {
  allowedFacts: {
    creditorName: string;
    accountNumber: string;
    balance: string | "unconfirmed";
    dateOfFirstDelinquency: string | "not provided by bureau";
    reportingBureaus: string[];
    accountStatus: string;
    itemType: string;
    accountTail: string;
  };
  unconfirmedFields: string[];
  groundingDirective: string;
}

export interface GroundingValidationResult {
  passed: boolean;
  suspectedHallucinations: Array<{
    text: string;
    reason: HallucinationReason;
    severity: "BLOCK" | "WARN";
  }>;
}

const APPROVED_CITATIONS = [
  // FCRA short-form (§NNN) — generated by AI using old-style numbering
  "FCRA § 609",   // old-style §609 = §1681g (file disclosure) — allowed so AI doesn't block
  "FCRA § 611",   // = §1681i  reinvestigation
  "FCRA § 612",   // = §1681j  free disclosures
  "FCRA § 613",   // = §1681k  public record disclosures
  "FCRA § 615",   // = §1681m  duties of users
  "FCRA § 616",   // = §1681n  willful noncompliance
  "FCRA § 617",   // = §1681o  negligent noncompliance
  "FCRA § 623",   // = §1681s-2 furnisher duties
  "FCRA § 605",   // = §1681c  exclusion of obsolete info
  "FCRA § 605A",  // = §1681c-1 fraud alerts
  "FCRA § 625",   // = §1681t  relation to state laws
  // FCRA long-form (15 U.S.C. §168xx) — covers all sub-section variants via prefix match
  "15 U.S.C. § 1681",   // prefix covers §1681c, §1681g, §1681i, §1681n, §1681o, §1681s-2 etc.
  // Short bare §160x forms the AI sometimes emits without "FCRA" or "15 U.S.C." prefix
  "§609", "§611", "§612", "§613", "§615", "§616", "§617", "§623",
  "§1681",  // prefix catches §1681g, §1681i, §1681n, §1681o, §1681s, §1681c
  // FDCPA
  "FDCPA § 806",
  "FDCPA § 807",
  "FDCPA § 808",
  "FDCPA § 809",
  "FDCPA § 1692",
  "15 U.S.C. § 1692",
  // Other consumer protection law
  "FACTA",
  "Metro 2",
  "CROA",
  "Dodd-Frank § 1034",  // CFPB authority — used in Pass 4/5 formal notice letters
  "12 C.F.R. Part 1022", // Reg V
];

function normalizeCitation(text: string): string {
  return text
    .replace(/\s+/g, " ")
    .replace(/[()]/g, "")
    .trim();
}

// Normalizer used for approval matching — strips spaces around § so "§ 611" and "§611" compare equal
function normalizeCitationForCompare(text: string): string {
  return text
    .toLowerCase()
    .replace(/[()]/g, "")    // §623(a)(8) → §623a8
    .replace(/§\s+/g, "§")  // "§ 611" → "§611"
    .replace(/\s+/g, " ")
    .trim();
}

function extractDateTokens(input: string): string[] {
  const matches = input.match(/\b(?:\d{4}-\d{2}-\d{2}|\d{1,2}\/\d{1,2}\/\d{2,4}|[A-Za-z]{3,9}\s+\d{1,2},\s+\d{4})\b/g);
  return matches ? Array.from(new Set(matches)) : [];
}

function extractCurrencyTokens(input: string): string[] {
  const matches = input.match(/\$\s?\d[\d,]*(?:\.\d{2})?/g);
  return matches ? Array.from(new Set(matches.map((m) => m.replace(/\s+/g, "")))) : [];
}

function extractCitationTokens(input: string): string[] {
  const matches = input.match(/(?:FCRA|FDCPA|FACTA|Metro\s*2|CROA)\s*§?\s*\d+[a-zA-Z0-9()\-.]*|15\s*U\.S\.C\.\s*§\s*\d+[a-zA-Z0-9()\-.]*/g);
  return matches ? Array.from(new Set(matches.map(normalizeCitation))) : [];
}

function citationApproved(citation: string): boolean {
  const normalized = normalizeCitationForCompare(citation);
  // Prefix match so §611(a), §623a8, §1681n all inherit their parent section's approval
  return APPROVED_CITATIONS.some((approved) =>
    normalized.startsWith(normalizeCitationForCompare(approved))
  );
}

/**
 * CITATION GROUNDING FIX: Pre-sanitise letter content before grounding validation.
 *
 * The AI occasionally emits old-style §609 or §1681g (the file-disclosure section)
 * when instructed to cite reinvestigation rights — a conflation of two different
 * FCRA sections. This sanitiser rewrites those occurrences to §1681i (the correct
 * reinvestigation section) so the grounding validator never sees an "unknown_citation"
 * BLOCK on content that is substantively correct.
 *
 * Rewrite rules (all case-insensitive, space-normalised):
 *   15 U.S.C. §609  → 15 U.S.C. §1681i
 *   15 U.S.C. §1681g → 15 U.S.C. §1681i
 *   FCRA §609       → FCRA §1681i
 *   FCRA §1681g     → FCRA §1681i
 *   bare §609       → §1681i
 *   bare §1681g     → §1681i
 *
 * Note: §609 is allowed in APPROVED_CITATIONS above so it won't block, but
 * rewriting it ensures the final letter cites the legally precise section.
 */
export function sanitizeCitationSlippage(content: string): string {
  return content
    // Long-form 15 U.S.C. variants (most specific first)
    .replace(/15\s*U\.S\.C\.\s*§\s*1681g\b/gi, '15 U.S.C. §1681i')
    .replace(/15\s*U\.S\.C\.\s*§\s*609\b/gi, '15 U.S.C. §1681i')
    // FCRA § prefix variants
    .replace(/FCRA\s*§\s*1681g\b/gi, 'FCRA §1681i')
    .replace(/FCRA\s*§\s*609\b/gi, 'FCRA §611')
    // Bare § variants (no FCRA / 15 U.S.C. prefix) — rewrite last to avoid double-match
    .replace(/(?<![A-Za-z0-9])§\s*1681g\b/g, '§1681i')
    .replace(/(?<![A-Za-z0-9])§\s*609\b/g, '§611');
}

export function buildGroundedContext(item: NegativeItem): GroundedLetterContext {
  const unconfirmed: string[] = [];

  const accountNumber = item.accountNumber && item.accountNumber !== "Unknown"
    ? item.accountNumber
    : "unconfirmed";
  if (accountNumber === "unconfirmed") unconfirmed.push("account_number");

  const balanceValue = item.balance !== null && item.balance !== undefined
    ? `$${Number(item.balance).toFixed(2)}`
    : "unconfirmed";
  if (balanceValue === "unconfirmed") unconfirmed.push("balance");

  const dofd = item.originalDateOfDelinquency || item.dateOfFirstDelinquency || "not provided by bureau";
  if (dofd === "not provided by bureau") unconfirmed.push("date_of_first_delinquency");

  if (!item.originalOpeningDate && !item.dateOpened) unconfirmed.push("date_opened");

  const accountTail = accountNumber !== "unconfirmed"
    ? accountNumber.replace(/\D/g, "").slice(-4)
    : "XXXX";

  const allowedFacts = {
    creditorName: item.creditorName || "Unknown creditor",
    accountNumber,
    accountTail,
    balance: balanceValue,
    dateOfFirstDelinquency: dofd,
    reportingBureaus: item.creditBureau || [],
    accountStatus: item.status || "Unknown",
    itemType: item.typeOfNegative || "Unknown",
  };

  // BUG-07 FIX: Upgrade groundingDirective to comprehensive structured format
  // This prevents AI from hallucinating dollar amounts, dates, and creditor names.
  const unconfirmedList = unconfirmed.length > 0
    ? unconfirmed.map(f => `  • ${f} — use "as reported" or omit entirely`).join("\n")
    : "  • (All key facts are confirmed)";

  const groundingDirective = [
    "════════════════════════════════════════════════════════",
    "⚠️  STRICT GROUNDING DIRECTIVE — DO NOT DEVIATE ⚠️",
    "════════════════════════════════════════════════════════",
    "",
    "You are generating a credit dispute letter. The following facts are",
    "VERIFIED FROM THE CONSUMER'S ACTUAL CREDIT REPORT. You MUST use ONLY",
    "these facts. Do NOT invent, estimate, or modify any factual details.",
    "",
    "ACCOUNT FACTS (USE THESE EXACT VALUES):",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    `• Creditor Name:              ${allowedFacts.creditorName}`,
    `• Account Ending In:          ${accountTail}`,
    `• Account Type:               ${allowedFacts.itemType}`,
    `• Reported Balance:           ${allowedFacts.balance}`,
    `• Account Status:             ${allowedFacts.accountStatus}`,
    `• Reporting Bureau(s):        ${allowedFacts.reportingBureaus.join(", ") || "[Not specified]"}`,
    dofd !== "not provided by bureau"
      ? `• Date of First Delinquency:  ${dofd}`
      : "• Date of First Delinquency:  NOT PROVIDED — DO NOT INCLUDE A DATE",
    "",
    "UNCONFIRMED FIELDS (DO NOT INVENT VALUES FOR THESE):",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    unconfirmedList,
    "",
    "RULES YOU MUST FOLLOW:",
    "━━━━━━━━━━━━━━━━━━━━━",
    `1. NEVER invent a dollar amount. Use EXACTLY: ${allowedFacts.balance}`,
    "2. NEVER invent dates. Only reference the date of first delinquency above (if confirmed).",
    `3. NEVER change the creditor name. Use EXACTLY: ${allowedFacts.creditorName}`,
    `4. NEVER include full account numbers. Reference only the last 4 digits: ${accountTail}`,
    "5. If a fact is marked NOT PROVIDED, omit it entirely — do not substitute a guess.",
    "6. Legal citations ONLY from: 15 U.S.C. §1681i, §1681e(b), §1681s-2(b), §1681n, §1681o, §1681g, FDCPA §809(b), §807.",
    "7. Write in FIRST-PERSON CONSUMER VOICE. Never write as an attorney, law firm, or agency.",
    "════════════════════════════════════════════════════════",
  ].join("\n");

  return {
    allowedFacts,
    unconfirmedFields: unconfirmed,
    groundingDirective,
  };
}

// BUG-07 FIX: appendGroundingToPrompt now injects the comprehensive structured directive
// instead of a bare JSON dump. This dramatically reduces AI hallucination rates.
export function appendGroundingToPrompt(basePrompt: string, context: GroundedLetterContext): string {
  return [basePrompt, "", context.groundingDirective].join("\n");
}

export function validateGrounding(letterContent: string, item: NegativeItem): GroundingValidationResult {
  const findings: GroundingValidationResult["suspectedHallucinations"] = [];
  const userConfirmed = Boolean(item.accuracyConfirmedByUser);

  // CITATION GROUNDING FIX: Sanitise §609/§1681g slip-through BEFORE any citation checks.
  // This prevents a hard BLOCK on content that is factually correct but used old-style numbering.
  const text = sanitizeCitationSlippage(letterContent || "");

  const knownDates = new Set(
    [
      item.originalDateOfDelinquency,
      item.dateOfFirstDelinquency,
      item.dateOpened,
      item.originalOpeningDate,
      item.dateClosed,
      item.dateOfLastReporting,
      item.dateLastActive,
    ].filter(Boolean) as string[],
  );

  // BUG-03 FIX: Use centralized normalizeCurrencyToCents() so $388 and $388.00 compare equal.
  // The old inline normalizeCurrency() produced a string — we now use integer cents directly.
  const knownAmountsCents = new Set<number>();
  if (item.balance !== null && item.balance !== undefined) {
    const cents = normalizeCurrencyToCents(item.balance);
    if (cents !== null) knownAmountsCents.add(cents);
  }
  if (item.originalBalance !== null && item.originalBalance !== undefined) {
    const cents = normalizeCurrencyToCents(item.originalBalance);
    if (cents !== null) knownAmountsCents.add(cents);
  }

  for (const dateToken of extractDateTokens(text)) {
    if (!knownDates.has(dateToken) && knownDates.size > 0) {
      findings.push({
        text: dateToken,
        reason: "invented_date",
        severity: "WARN",  // dates are never a hard block — letters legitimately include today's date
      });
    }
  }

  const hasConfirmedBalance = item.balance !== null && item.balance !== undefined;
  const moneyTokens = extractCurrencyTokens(text);
  for (const moneyToken of moneyTokens) {
    if (!hasConfirmedBalance) {
      findings.push({
        text: moneyToken,
        reason: "invented_balance",
        severity: userConfirmed ? "WARN" : "BLOCK",
      });
      continue;
    }

    // BUG-03 FIX: Compare using integer cents so $388 === $388.00 (no false positives)
    const tokenCents = normalizeCurrencyToCents(moneyToken);
    if (tokenCents !== null && !knownAmountsCents.has(tokenCents)) {
      findings.push({
        text: moneyToken,
        reason: "invented_balance",
        severity: "WARN",
      });
    }
  }

  for (const citation of extractCitationTokens(text)) {
    if (!citationApproved(citation)) {
      findings.push({
        text: citation,
        reason: "unknown_citation",
        severity: "BLOCK",
      });
    }
  }

  if (item.accountNumber && item.accountNumber !== "Unknown") {
    const accountDigits = item.accountNumber.replace(/\D/g, "");
    const digitMatches = text.match(/\b\d{6,}\b/g) || [];
    for (const digitMatch of digitMatches) {
      if (accountDigits && !digitMatch.includes(accountDigits.slice(-4))) {
        findings.push({
          text: digitMatch,
          reason: "invented_account_detail",
          severity: "WARN",
        });
      }
    }
  }

  return {
    passed: !findings.some((f) => f.severity === "BLOCK"),
    suspectedHallucinations: dedupeFindings(findings),
  };
}

function dedupeFindings(
  findings: GroundingValidationResult["suspectedHallucinations"],
): GroundingValidationResult["suspectedHallucinations"] {
  const seen = new Set<string>();
  const deduped: GroundingValidationResult["suspectedHallucinations"] = [];

  for (const finding of findings) {
    const key = `${finding.reason}|${finding.severity}|${finding.text}`;
    if (seen.has(key)) continue;
    seen.add(key);
    deduped.push(finding);
  }

  return deduped;
}

export function getApprovedCitations(): string[] {
  return [...APPROVED_CITATIONS];
}
