/**
 * LetterAuditBadge.tsx — World-Class §8.2 Intelligence & Audit Badge
 *
 * Displays the LetterGenerationOrchestrator provenance trail on every letter
 * card so the user always knows exactly how their dispute letter was produced:
 *
 *   🤖 AI Primary        — clean AI draft, all compliance gates passed
 *   🔧 AI Repaired       — AI draft fixed by the targeted JSON repair pass
 *   🛡️ Verified Metro 2 Template — deterministic on-device fallback (Tier 4)
 *
 * Plus the letter's uniqueness score and its controlling statutory authority.
 */

import React from 'react';

export type LetterSourceType = 'ai_primary' | 'ai_repaired' | 'deterministic_fallback';

export interface LetterAuditBadgeProps {
  sourceType: LetterSourceType;
  uniquenessScore?: number | null;
  statutoryAnchor?: string;
  auditExplanation?: string;
}

const BADGE_CONFIG: Record<LetterSourceType, { label: string; color: string; title: string }> = {
  ai_primary: {
    label: '🤖 AI Primary (Groq/Gemini)',
    color: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
    title: 'Generated by the primary AI cascade — all compliance and anchor gates passed.',
  },
  ai_repaired: {
    label: '🔧 AI Repaired (Targeted Fix)',
    color: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
    title: 'AI draft repaired by the targeted JSON remediation pass to resolve style/voice/anchor findings.',
  },
  deterministic_fallback: {
    label: '🛡️ Verified Metro 2 Template',
    color: 'bg-purple-500/20 text-purple-300 border-purple-500/40',
    title: 'Rendered on-device by the deterministic Metro 2 template engine — zero API dependency, full factual grounding.',
  },
};

export const LetterAuditBadge: React.FC<LetterAuditBadgeProps> = ({
  sourceType,
  uniquenessScore,
  statutoryAnchor,
  auditExplanation,
}) => {
  const config = BADGE_CONFIG[sourceType] ?? BADGE_CONFIG.deterministic_fallback;

  return (
    <div
      className="flex flex-wrap items-center gap-2 py-2 px-3 rounded-lg bg-gray-900/80 border border-gray-800 text-xs"
      title={auditExplanation || config.title}
    >
      <span className={`px-2.5 py-0.5 rounded-full font-semibold border ${config.color}`}>
        {config.label}
      </span>
      {typeof uniquenessScore === 'number' && (
        <span className="text-gray-400 font-mono">
          Uniqueness: <strong className="text-gray-200">{uniquenessScore}%</strong>
        </span>
      )}
      {typeof uniquenessScore === 'number' && statutoryAnchor && (
        <span className="text-gray-600">|</span>
      )}
      {statutoryAnchor && (
        <span className="text-gray-400 font-mono">
          Authority: <strong className="text-gray-200">{statutoryAnchor}</strong>
        </span>
      )}
    </div>
  );
};
